FROM resin/raspberry-pi-python

ENV INITSYSTEM on

# Set our working directory
WORKDIR /usr/src/app

# This will copy all files in our root to the working  directory in the container
COPY . ./

CMD ["./gate-god"]
